spring:
  r2dbc:
    url: r2dbc:postgresql://carvajal_db:5432/carvajal
    username: c9ba0d41b19f917f6f853f5adaf185d0
    password: 8165c6fcfc2d73314e9e3713500856d6
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: false
#    hibernate:

  jwt:
    secret: "MUVFQTJCQkFCMzI0MzkyM0E5QjlGNTU2REMyNDlEQTdEMjUyMUNBODFDQkE4"